DROP TRIGGER IF EXISTS validate_game;
DELIMITER $$

CREATE TRIGGER validate_game BEFORE INSERT ON games
FOR EACH ROW
BEGIN
    IF NEW.PLAYER_1_ID NOT IN (SELECT USER_ID FROM ladder_user WHERE LADDER_ID = NEW.LADDER_ID) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'PLAYER 1 NOT IN LADDER';
    ELSEIF NEW.PLAYER_2_ID NOT IN (SELECT USER_ID FROM ladder_user WHERE LADDER_ID = NEW.LADDER_ID) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'PLAYER 2 NOT IN LADDER';
    END IF;
END$$

DELIMITER ;